version: '3.3'

services:
  redis:
    image: redis:7.0
    volumes:
      - redisdata:/data


  postgres:
    image: postgres:13
    env_file:
      - ./postgres/.env
    volumes:
      - itmo_bot_data:/var/lib/postgresql/data
    restart: always

  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    depends_on:
      - redis
      - postgres

volumes:
  redisdata:
  itmo_bot_data: