version: '3.3'

services:
  redis:
    image: redis:7.0
    volumes:
      - redisdata:/data


  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    volumes:
      - ./p3110_data:/bot/database/database_file
    depends_on:
      - redis

volumes:
  redisdata: